### ISSUE TITLE
Cannot find module '../cli'

### ISSUE THREAD

**Issue by kruug** [valeriangalliat/gogs-migrate#1]
Attempting to run Gogs-Migrate on both Windows and Debian.  Both throw the error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module '../cli'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/kruug/workspace/gogs-migrate/bin/gogs-migrate:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

This was running just `gogs-migrate` as well as `gogs-migrate -h`.

**Comment by valeriangalliat** [comment]
Hi! Since you seem to not have installed gogs-migrate with npm, you have to install the dependencies and compile it before usage; jsut run `npm install` in the project folder and it should work!

**Comment by kruug** [comment]
Yup, I see that you just added installation instructions.  I'll give this a shot!  Thanks!

**Comment by valeriangalliat** [comment]
@kruug Cool, let me know if it solved your problem. :)
